"""Run Django's upstream `tests/template_tests/` against oxide.

Sparse-clones Django at a tag, swaps in `OxideTemplates` as the default
backend, then invokes Django's own testrunner over `template_tests`.

Usage:

    python scripts/sync_django_tests.py [--django-tag TAG] [--pattern GLOB]
"""

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

DEFAULT_TAG = "6.0"
CACHE_ROOT = Path.home() / ".cache" / "django-template-oxide"


def clone_django(tag: str) -> Path:
    """Sparse-clone Django at `tag` into the cache. Returns the path."""
    target = CACHE_ROOT / f"django-{tag}"
    if (target / "django" / "__init__.py").exists():
        return target

    CACHE_ROOT.mkdir(parents=True, exist_ok=True)
    print(f"[sync] cloning django {tag} into {target}")
    subprocess.run(
        [
            "git",
            "clone",
            "--depth",
            "1",
            "--filter=blob:none",
            "--sparse",
            "--branch",
            tag,
            "https://github.com/django/django.git",
            str(target),
        ],
        check=True,
    )
    subprocess.run(
        ["git", "sparse-checkout", "set", "django", "tests/template_tests"],
        check=True,
        cwd=target,
    )
    return target


def make_settings_module(django_root: Path) -> Path:
    """Generate a settings.py that activates OxideTemplates and points
    the loader at Django's template_tests fixtures."""
    settings = django_root / "_oxide_template_tests_settings.py"
    settings.write_text(
        """# Auto-generated by scripts/sync_django_tests.py, do not edit.
import os

SECRET_KEY = "oxide-template-tests"

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "template_tests",
]

DATABASES = {
    "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"},
}

# OxideTemplates is the only configured backend.
_TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "tests", "template_tests", "templates")
TEMPLATES = [
    {
        "BACKEND": "django_template_oxide.backend.OxideTemplates",
        "DIRS": [_TEMPLATE_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [],
            "debug": True,
        },
    },
]

ROOT_URLCONF = "template_tests.alternate_urls"
USE_TZ = True
"""
    )
    return settings


def run_template_tests(django_root: Path, pattern: str) -> int:
    """Invoke Django's own `tests/runtests.py` with our oxide-backed
    settings. Returns the testrunner's exit code. We use runtests.py
    (not `python -m django test`) because it sets up sys.path so
    `template_tests` is importable as a top-level package."""
    env = os.environ.copy()
    # Put Django's source at the front of sys.path so `import django`
    # picks up the cloned version, not the one in our venv.
    env["PYTHONPATH"] = f"{django_root}{os.pathsep}{env.get('PYTHONPATH', '')}"
    env["DJANGO_SETTINGS_MODULE"] = "_oxide_template_tests_settings"

    test_label = f"template_tests.{pattern}" if pattern else "template_tests"
    cmd = [
        sys.executable,
        "tests/runtests.py",
        test_label,
        "--verbosity=2",
        "--noinput",
        "--settings=_oxide_template_tests_settings",
        # Parallel mode pickles tracebacks across process boundaries,
        # which fails on traceback objects with C-frame state (common
        # in template-rendering errors). Stick to single-process.
        "--parallel=1",
    ]
    print(f"[sync] {' '.join(cmd)}  (cwd={django_root})")
    return subprocess.run(cmd, env=env, cwd=django_root).returncode


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--django-tag",
        default=DEFAULT_TAG,
        help=f"Django git tag to test against (default: {DEFAULT_TAG})",
    )
    parser.add_argument(
        "--pattern",
        default="",
        help="Test path under template_tests/ (e.g. 'test_basic', 'syntax_tests.test_if')",
    )
    args = parser.parse_args()

    django_root = clone_django(args.django_tag)
    make_settings_module(django_root)
    return run_template_tests(django_root, args.pattern)


if __name__ == "__main__":
    sys.exit(main())
